language: go
go:
  - "1.14.1"
services:
  - docker
sudo: required
install:
  - go get -u golang.org/x/lint/golint
  - GO111MODULE=on go mod vendor
  - (cd testenv/roach_clip && make install)
before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...
  - make testenv
  # give database time to start
  - sleep 10

script:
  - go fmt ./...
  - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build