
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "feat/payments"
  name = "github.com/RTradeLtd/config"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
